### ISSUE TITLE
Save lines in history file with a Unix timestamp

### ISSUE THREAD

**Issue by avinashkanaujiya** [kkawakam/rustyline#442] opened 2020-09-29 17:20 UTC
Just What I said above...

**Comment by gwenn** [comment] 2020-10-03 08:13
Maybe we should introduce a Trait like [termwiz](https://docs.rs/termwiz/0.9.0/termwiz/lineedit/trait.History.html) and provide only a default implementation ?

**Comment by walles** [comment] 2022-01-01 09:36
Should this ticket be marked as a duplicate of #127?

With custom history load / save functionality people could add whatever they wanted, and this ticket would be up to the crate users to deal with.

**Comment by gwenn** [comment] 2022-02-23 18:31
2 years later => #604
Feedback is welcome.

**Closed** 2023-01-15 15:30 UTC
Labels: enhancement

**Comment by gwenn** [comment] 2023-02-19 09:43
Version 11.0.0 released.
